#!/bin/bash

# Get git commit information
COMMIT_HASH=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
COMMIT_DATE=$(git log -1 --format=%cd --date=short 2>/dev/null || echo "unknown")
COMMIT_MESSAGE=$(git log -1 --format=%s 2>/dev/null || echo "Development build")

# Generate the TypeScript file
cat > src/git-info.ts <<EOF
// This file is auto-generated by scripts/generate-git-info.sh
export const GIT_INFO = {
  commitHash: "$COMMIT_HASH",
  commitDate: "$COMMIT_DATE",
  commitMessage: "$COMMIT_MESSAGE",
}
EOF

echo "Git info generated: commit=$COMMIT_HASH, date=$COMMIT_DATE, message=$COMMIT_MESSAGE"
